name: Development actions

on:
  push:
    branches: ["development"]

jobs:
  build:
    strategy:
      matrix:
        config: [
          { target: android, os: macos-latest, tasks: testDebugUnitTest testReleaseUnitTest, continueOnError: false },
          { target: ios, os: macos-latest, tasks: iosSimulatorArm64Test iosX64Test, continueOnError: false }
        ]
    runs-on: ${{ matrix.config.os }}
    name: Build and test ${{ matrix.config.target }}
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: KSP generator
        run: ./gradlew :shared:kspCommonMainKotlinMetadata

      - name: Test ${{ matrix.config.target }} targets
        continue-on-error: ${{ matrix.config.continueOnError }}
        run: ./gradlew :library:${{ matrix.config.tasks }}

  release:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: macos-latest
    needs:
      - build
    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Publish Annotation to Sonatype
        run:  > 
          ./gradlew :annotation:publishAllPublicationsToMavenCentral
          -Penv=dev
          -PmavenCentralUsername=${{ secrets.MAVEN_USERNAME }}
          -PmavenCentralPassword=${{ secrets.MAVEN_PASSWORD }}
          -PsigningInMemoryKey=${{ secrets.SIGNING_KEY }}
          -PsigningInMemoryKeyPassword=${{ secrets.SIGNING_PASSWORD }}

      - name: Publish Processor to Sonatype
        run:  > 
          ./gradlew :processor:publishAllPublicationsToMavenCentral
          -Penv=dev
          -PmavenCentralUsername=${{ secrets.MAVEN_USERNAME }}
          -PmavenCentralPassword=${{ secrets.MAVEN_PASSWORD }}
          -PsigningInMemoryKey=${{ secrets.SIGNING_KEY }}
          -PsigningInMemoryKeyPassword=${{ secrets.SIGNING_PASSWORD }}

      - name: Publish Library to Sonatype
        run:  > 
          ./gradlew :library:publishAllPublicationsToMavenCentral
          -Penv=dev
          -PmavenCentralUsername=${{ secrets.MAVEN_USERNAME }}
          -PmavenCentralPassword=${{ secrets.MAVEN_PASSWORD }}
          -PsigningInMemoryKey=${{ secrets.SIGNING_KEY }}
          -PsigningInMemoryKeyPassword=${{ secrets.SIGNING_PASSWORD }}
